=== OctopusDeploy/kubernetes-agent-tools-base/versions.schema.json
{  
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "kubernetes-agent-tools-base versions",
  "type": "object",
  "properties": {
    "tools": {
      "type": "object",
      "properties": {
        "kubectl": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "helm": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "powershell": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "kubectl",
        "helm",
        "powershell"
      ]
    },
    "latest": {
      "type": "string",
      "minLength": 1,
      "maxLength": 4
    },
    "revisionHash": {
      "type": "string",
      "minLength": 1,
      "maxLength": 6
    },
    "deprecations": {
      "type": "object",
      "pattenProperties": {
        ".*": {
          "type": "object",
          "properties": {
            "latestTag": {
              "type": "string",
              "minLength": 1
            }
          },
          "required": [
            "latestTag"
          ]
        }
      }
    }
  },
  "required": [
    "tools",
    "latest",
    "revisionHash",
    "deprecations"
  ]
}

=== OctopusDeploy/kubernetes-agent-tools-base/versions.json
{
  "tools": {
    "kubectl": [
      "1.35.2",
      "1.34.5",
      "1.33.9",
      "1.32.13"
    ],
    "helm": [
      "3.20.1"
    ],
    "powershell": [
      "7.6.0"
    ]
  },
  "latest": "1.34",
  "revisionHash": "jBhJpN",
  "deprecations": {
    "1.26": {
      "latestTag": "1.26@sha256:a0892db7be9d668eceba2ce0c56ed82b2a58ff205ffea27a98e40825143b63f0"
    },
    "1.27": {
      "latestTag": "1.27@sha256:9d1ce87c37a33582bd3bb0b2e2d54d7a6bc0e71d659a1132acd3893c9645a507"
    },
    "1.28": {
      "latestTag": "1.28@sha256:c2a7c7d230b2c959c4228f0860d5d6dca143a38fa037911fc5dd0319a0cf1ed0"
    },
    "1.29": {
      "latestTag": "1.29@sha256:a47d5221bf5ba679b03c5c9cf05d9569e5074f5897f8f92b6cf435bca7e6f2ae"
    },
    "1.30": {
      "latestTag": "1.30@sha256:b7c6e77591dcf9023b6a547ab4768c2fb297f1c65cbdac1510dfd3a90c5cf4db"
    },
    "1.31": {
      "latestTag": "1.31@sha256:be6a25ab4a2cea435c33b467c648464fbbe9776b08f3e87e3a6901943c68545e"
    }
  }
}
